###############
## NAMESPACE ##
###############
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo
---
################
## DEPLOYMENT ##
################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: podinfo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - image: stefanprodan/podinfo:latest
        imagePullPolicy: Always
        name: podinfo
        ports:
        - containerPort: 9898
          name: http
          protocol: TCP
        #env:
        #- name: TITLE
        #  value: "AKS Ingress Demo"        
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 20m
        #    memory: 20Mi
      #imagePullSecrets:
      #- name: acr-secret
      restartPolicy: Always            
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Exists"
          effect: "NoSchedule"      
---
#############
## SERVICE ##
#############
apiVersion: v1
kind: Service
metadata:
  name: podinfo-service
  namespace: podinfo
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: podinfo    
  sessionAffinity: None
---
#############
## INGRESS ##
#############
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: podinfo
  annotations:
    kubernetes.io/ingress.class: nginx
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/use-regex: "true"
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  #- host: "*.foo.com"
  #-  http:
  - host: "ingress-podinfo.btotest.com"
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: podinfo-service
            port:
              number: 80
---
#########
## HPA ##
#########
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: podinfo-hpa
  namespace: podinfo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  #- type: Pods
  #  pods:
  #    metric:
  #      name: packets-per-second
  #    target:
  #      type: AverageValue
  #      averageValue: 1k
  #- type: Object
  #  object:
  #    metric:
  #      name: requests-per-second
  #    describedObject:
  #      apiVersion: networking.k8s.io/v1
  #      kind: Ingress
  #      name: main-route
  #    target:
  #      type: Value
  #      value: 10k
